### ISSUE TITLE
empty tar file

### ISSUE THREAD

**Issue by wmmghc** [duckduckgo/smarter-encryption#5]
downloading the file "smarter_encryption_latest.tgz" found on page/uri https://github.com/duckduckgo/smarter-encryption at link "publicly available" (http://staticcdn.duckduckgo.com/https/smarter_encryption_latest.tgz) results in an empty file.

unless i'm doing something wrong... :-)

**Comment by dharb** [comment]
@wmmghc how are you downloading the file? I just did a quick check in Firefox/Windows and clicking that link starts the download, which is 126MB. Unarchiving this file shows LICENSE, README, and smarter_encryption.txt (which is 468MB).

**Comment by wmmghc** [comment]
thanks for the uber quick reply!

as it turns out, i just re-examined the downloaded file and it is there, 
apparently a time related issue.  my apologies for the false flag.  FF 
gave no indication of being 'in progress' for the download, so i assumed 
it was complete, having waited a seemingly approp amount of time.  
apparently not.
and, yes, that's what it made out of me. :(           sigh...

original:
 > ls -l ~/smarter_encryption_latest.tgz
-rw-r--r-- 1 wmm wmm 0 Oct  2 11:37 smarter_encryption_latest.tgz

now (much later):
 > ls -l ~/smarter_encryption_latest.tgz
total 129388
-rw-rw-r-- 1 wmm wmm 132485923 Oct  2 11:41 smarter_encryption_latest.tgz

again, apologies.  and thank you to you and yours for what is prob'ly a 
mostly thankless job.

**Comment by dharb** [comment]
No problem at all, happy to see this data being used 😃
